name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - live

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Ensure this matches your Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Angular CLI
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      # Step 5: Build the Angular app
      - name: Build Angular App
        run: npm run build -- --configuration production

      # Step 6: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_LIVE_REFLACTIVE_RESUME_BUILDER }}"
          channelId: live
          projectId: live-reflactive-resume-builder
